version: '3.9'

services:
  fastapi:
    container_name: fastapi
    build: .
    command: uvicorn topic-suggestion.main:app --reload --host 0.0.0.0 --port 8000
    ports:
      - '8000:8000'
    volumes:
      - .:/code
    env_file:
      - .env

networks:
  backend: 
    driver: bridge
